version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: rental_db
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: usersDB
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: