spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/usersDB
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver  # Add this
    hikari:  # Connection pool settings
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  # Pretty print SQL
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 9090
  error:
    include-message: always
    include-binding-errors: always